# Generated by Django 3.0.5 on 2020-04-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='comment',
            field=models.TextField(default='sd'),
            preserve_default=False,
        ),
    ]
